const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',

    GET_USER: 'GET_USER',

    GET_PACKAGES: 'GET_PACKAGES',

    GET_TRANSACTIONPOINTS: 'GET_TRANSACTIONPOINTS',

    GET_WAREHOUSES: 'GET_WAREHOUSES'
}

export default actionTypes